// Stage 6: turn a placement plan into Keyman source files.
//   .kmn                    desktop rules (direct remaps, RALT specials, RALT restores)
//   .keyman-touch-layout    phone touch layout (default/shift/numeric layers)
//   .kvks                   on-screen visual keyboard (default/shift)
//
// Output formats were matched against release/h/hausa_kano/source/*.

import type { PlanResult } from './place.ts';
import type { Layout } from './layout.ts';
import { codepointHex } from './analyze.ts';

const uId = (ch: string) => 'U_' + codepointHex(ch);
const uPlus = (ch: string) => 'U+' + codepointHex(ch);

export interface KbMeta {
  id: string;
  name: string;
  font?: string;
  copyright?: string;
  version?: string;
}

// ---------------------------------------------------------------------------
// .kmn
// ---------------------------------------------------------------------------
export function emitKmn(planResult: PlanResult, layout: Layout, meta: KbMeta): string {
  const L: string[] = [];
  L.push(`c ${meta.name} -- generated by tools/kbgen (logic-driven character placement).`);
  L.push(`c Each rule below is explained by an objective anchor signal; see the .report.json.`);
  L.push(`store(&NAME) '${meta.name}'`);
  L.push(`store(&VERSION) '10.0'`);
  L.push(`store(&KEYBOARDVERSION) '${meta.version || '1.0'}'`);
  L.push(`store(&COPYRIGHT) '${meta.copyright || ''}'`);
  L.push(`store(&TARGETS) 'any'`);
  L.push(`store(&VISUALKEYBOARD) '${meta.id}.kvks'`);
  L.push(`store(&LAYOUTFILE) '${meta.id}.keyman-touch-layout'`);
  L.push('');
  L.push('begin Unicode > use(main)');
  L.push('');
  L.push('group(main) using keys');

  const direct: string[] = [], ralt: string[] = [], restore: string[] = [];
  for (const k of layout.keys) {
    const kp = planResult.keys.get(k.key);
    if (!kp) continue;
    if (kp.defOut != null) direct.push(`+ [${k.key}] > ${uPlus(kp.defOut)}    c ${kp.defOut}`);
    if (kp.shiftOut != null) direct.push(`+ [SHIFT ${k.key}] > ${uPlus(kp.shiftOut)}    c ${kp.shiftOut}`);
    // RALT outputs: a special (occupied anchor) or a restored base letter (displaced key).
    if (kp.raltDef != null) {
      const target = kp.defOut != null ? restore : ralt;
      target.push(`+ [RALT ${k.key}] > ${uPlus(kp.raltDef)}    c ${kp.raltDef}`);
    }
    if (kp.raltShift != null) {
      const target = kp.shiftOut != null ? restore : ralt;
      target.push(`+ [SHIFT RALT ${k.key}] > ${uPlus(kp.raltShift)}    c ${kp.raltShift}`);
    }
  }
  if (direct.length) { L.push('', 'c --- direct remaps on free anchor keys ---', ...direct); }
  if (ralt.length) { L.push('', 'c --- specials on RALT + visual/phonetic anchor ---', ...ralt); }
  if (restore.length) { L.push('', 'c --- restore displaced base letters (URLs, foreign words) ---', ...restore); }
  return L.join('\n') + '\n';
}

// ---------------------------------------------------------------------------
// .keyman-touch-layout
// ---------------------------------------------------------------------------
interface TouchKey {
  id: string;
  text: string;
  width?: string;
  sp?: string;
  nextlayer?: string;
  layer?: string;
  pad?: string;
  sk?: TouchKey[];
}

function letterKey(entry: { key: string; lower: string; upper: string }, isShift: boolean, kp: { defOut: string | null; shiftOut: string | null; skDef: string[]; skShift: string[] } | undefined): TouchKey {
  const baseChar = isShift ? entry.upper : entry.lower;
  const direct = kp && (isShift ? kp.shiftOut : kp.defOut);
  const sk = kp && (isShift ? kp.skShift : kp.skDef);
  const key: TouchKey = direct ? { id: uId(direct), text: direct } : { id: entry.key, text: baseChar };
  if (sk?.length) key.sk = sk.map((c) => ({ text: c, id: uId(c) }));
  return key;
}

function buildLetterLayer(id: string, isShift: boolean, planResult: PlanResult, layout: Layout) {
  const makeKey = (t: [string, string, string]) => letterKey({ key: t[0], lower: t[1], upper: t[2] }, isShift, planResult.keys.get(t[0]));

  const row1 = layout.rows[0].map(makeKey);
  const row2 = [...layout.rows[1].map(makeKey), { id: `T_spacer_${id}`, text: '', width: '10', sp: '10' }];
  const row3: TouchKey[] = [
    { id: 'K_SHIFT', text: '*Shift*', sp: isShift ? '2' : '1', nextlayer: isShift ? 'default' : 'shift' },
    ...layout.rows[2].map(makeKey),
    periodKey(isShift),
    { id: 'K_BKSP', text: '*BkSp*', width: '100', sp: '1' },
  ];
  const row4 = bottomRow();

  return { id, row: [{ id: 1, key: row1 }, { id: 2, key: row2 }, { id: 3, key: row3 }, { id: 4, key: row4 }] };
}

function periodKey(isShift: boolean): TouchKey {
  const k: TouchKey = { id: 'K_PERIOD', text: '.' };
  if (isShift) k.layer = 'default';
  k.sk = [
    { text: ',', id: 'K_COMMA', ...(isShift ? { layer: 'default' } : {}) },
    { text: '!', id: 'K_1', layer: 'shift' },
    { text: '?', id: 'K_SLASH', layer: 'shift' },
    { text: "'", id: 'K_QUOTE', ...(isShift ? { layer: 'default' } : {}) },
    { text: ':', id: 'K_COLON', layer: 'shift' },
    { text: ';', id: 'K_COLON', ...(isShift ? { layer: 'default' } : {}) },
  ];
  return k;
}

function bottomRow(): TouchKey[] {
  return [
    { id: 'K_NUMLOCK', text: '*123*', width: '150', sp: '1', nextlayer: 'numeric' },
    { id: 'K_LOPT', text: '*Menu*', width: '120', sp: '1' },
    { id: 'K_SPACE', text: '', width: '610', sp: '0' },
    { id: 'K_ENTER', text: '*Enter*', width: '150', sp: '1' },
  ];
}

// Standard numeric layer (kept generic; no language-specific currency).
function numericLayer() {
  return {
    id: 'numeric',
    row: [
      { id: 1, key: '1234567890'.split('').map((d) => ({ id: 'K_' + d, text: d })) },
      { id: 2, key: [
        { id: 'K_4', text: '$', layer: 'shift', pad: '50' },
        { id: 'K_2', text: '@', layer: 'shift' },
        { id: 'K_3', text: '#', layer: 'shift' },
        { id: 'K_5', text: '%', layer: 'shift' },
        { id: 'K_6', text: '&', layer: 'shift' },
        { id: 'K_HYPHEN', text: '_', layer: 'shift' },
        { id: 'K_EQUAL', text: '=', layer: 'default' },
        { id: 'K_BKSLASH', text: '|', layer: 'shift' },
        { id: 'K_BKSLASH', text: '\\', layer: 'default' },
        { id: 'T_spacer_num', text: '', width: '10', sp: '10' },
      ] },
      { id: 3, key: [
        { id: 'K_LBRKT', text: '[', pad: '110' },
        { id: 'K_9', text: '(', layer: 'shift' },
        { id: 'K_0', text: ')', layer: 'shift' },
        { id: 'K_RBRKT', text: ']' },
        { id: 'K_EQUAL', text: '+', layer: 'shift' },
        { id: 'K_HYPHEN', text: '-' },
        { id: 'K_8', text: '*', layer: 'shift' },
        { id: 'K_SLASH', text: '/' },
        { id: 'K_BKSP', text: '*BkSp*', width: '100', sp: '1' },
      ] },
      { id: 4, key: [
        { id: 'K_LOWER', text: '*abc*', width: '150', sp: '1', nextlayer: 'default' },
        { id: 'K_LOPT', text: '*Menu*', width: '120', sp: '1' },
        { id: 'K_SPACE', text: '', width: '610', sp: '0' },
        { id: 'K_ENTER', text: '*Enter*', width: '150', sp: '1' },
      ] },
    ],
  };
}

export function emitTouch(planResult: PlanResult, layout: Layout, meta: KbMeta): string {
  const obj = {
    phone: {
      font: meta.font || 'Tahoma',
      layer: [
        buildLetterLayer('default', false, planResult, layout),
        buildLetterLayer('shift', true, planResult, layout),
        numericLayer(),
      ],
    },
  };
  return JSON.stringify(obj, null, 2) + '\n';
}

// ---------------------------------------------------------------------------
// .kvks (on-screen visual keyboard). Reflects direct remaps; RALT specials are not
// shown on the visual keyboard (they live on the modifier layer / touch longpress).
// ---------------------------------------------------------------------------
const PUNCT: [string, string, string][] = [
  ['K_BKQUOTE', '`', '~'], ['K_1', '1', '!'], ['K_2', '2', '@'], ['K_3', '3', '#'],
  ['K_4', '4', '$'], ['K_5', '5', '%'], ['K_6', '6', '^'], ['K_7', '7', '&'],
  ['K_8', '8', '*'], ['K_9', '9', '('], ['K_0', '0', ')'], ['K_HYPHEN', '-', '_'],
  ['K_EQUAL', '=', '+'], ['K_LBRKT', '[', '{'], ['K_RBRKT', ']', '}'], ['K_BKSLASH', '\\', '|'],
  ['K_COLON', ';', ':'], ['K_QUOTE', "'", '"'], ['K_COMMA', ',', '<'], ['K_PERIOD', '.', '>'],
  ['K_SLASH', '/', '?'],
];
const xmlEsc = (s: string) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

export function emitKvks(planResult: PlanResult, layout: Layout, meta: KbMeta): string {
  const rowsFor = (isShift: boolean) => {
    const letterKeys = layout.keys.map((k) => {
      const kp = planResult.keys.get(k.key);
      const direct = kp && (isShift ? kp.shiftOut : kp.defOut);
      const ch = direct ?? (isShift ? k.upper : k.lower);
      return `      <key vkey="${k.key}">${xmlEsc(ch)}</key>`;
    });
    const punctKeys = PUNCT.map(([vk, lo, up]) =>
      `      <key vkey="${vk}">${xmlEsc(isShift ? up : lo)}</key>`
    );
    return [...letterKeys, ...punctKeys].join('\n');
  };

  return [
    '<?xml version="1.0" encoding="utf-8"?>',
    '<visualkeyboard>',
    '  <header>',
    '    <version>10.0</version>',
    `    <kbdname>${meta.id}</kbdname>`,
    '    <flags/>',
    '  </header>',
    '  <encoding name="unicode" fontname="Arial" fontsize="-12">',
    '    <layer shift="">',
    rowsFor(false),
    '    </layer>',
    '    <layer shift="S">',
    rowsFor(true),
    '    </layer>',
    '  </encoding>',
    '</visualkeyboard>',
    '',
  ].join('\n');
}
