// Shared helpers for the checks/docs/* (spec 076 US7 / FR-019) documentation
// checks — internal to this directory.
//
// These checks work over the plain rendered/current text of the six shipped
// documentation members (`DocLintInput.members`, contracts `doc-members.ts`
// §7), never the VFS or a parsed DOM: keyboard-lint stays contracts-only
// (dep-cruiser rule `lint-not-to-engine`) and node-clean (no DOM APIs). The
// 11.5 criterion text says "in-browser check via DOMParser" — this package
// implements the same *fact* (unbalanced/unclosed HTML elements) with a small
// dependency-free tag-balance scanner instead, a deliberate deviation from
// the criterion's suggested mechanism (spec 076 research R7). It binds the
// fact checked, not the API.

import type { DocLintInput, DocMemberId } from "@keyboard-studio/contracts";

// ---------------------------------------------------------------------------
// Member paths
// ---------------------------------------------------------------------------

// The member -> projected-path rule is the contracts package's `docMemberPath`
// (one copy shared with the engine's tier derivation); re-exported for the
// check modules and the barrel.
export { docMemberPath } from "@keyboard-studio/contracts";

/** Convenience accessor: a member's current text from `DocLintInput`, or `undefined`. */
export function memberText(input: DocLintInput, member: DocMemberId): string | undefined {
  return input.members[member];
}

// ---------------------------------------------------------------------------
// HISTORY.md parsing (3.3, 3.4, 3.5, 3.6/7.1, 3.7)
// ---------------------------------------------------------------------------

/**
 * One parsed HISTORY.md entry. Entries are ATX headings (`## <version>
 * (<date>)`) as generated by the scaffolder / adapt-staging (spec 059/064) —
 * NOT the setext/hyphen-underline style the criteria prose describes, which
 * predates the tool's own generator. `version`/`date` are `null` when the
 * heading text doesn't match the `<version> (<date>)` shape at all.
 */
export interface HistoryEntry {
  /** Heading text after "## ", e.g. "1.2 (2024-03-01)". */
  headingRaw: string;
  version: string | null;
  date: string | null;
  /** True iff `date` matches `YYYY-MM-DD`. */
  dateValid: boolean;
  /** Bullet content, marker (`*` or `-`) and surrounding whitespace stripped. */
  bullets: string[];
  /** Non-blank body lines that are neither blank nor a recognised bullet. */
  strayLines: string[];
}

const ENTRY_HEADING_RE = /^(\S+)\s+\(([^)]*)\)\s*$/;
const HISTORY_DATE_RE = /^\d{4}-\d{2}-\d{2}$/;
const BULLET_RE = /^[*-]\s+(.*)$/;

/** Parse a HISTORY.md text into its entries, in file order (top first). */
export function parseHistoryEntries(text: string): HistoryEntry[] {
  const lines = text.split(/\r\n|\r|\n/);
  const headingIdxs: number[] = [];
  for (let i = 0; i < lines.length; i++) {
    if (/^##\s+/.test(lines[i] ?? "")) headingIdxs.push(i);
  }

  const entries: HistoryEntry[] = [];
  for (let h = 0; h < headingIdxs.length; h++) {
    const start = headingIdxs[h]!;
    const end = h + 1 < headingIdxs.length ? headingIdxs[h + 1]! : lines.length;
    const headingRaw = (lines[start] ?? "").replace(/^##\s+/, "").trim();
    const m = ENTRY_HEADING_RE.exec(headingRaw);
    const version = m ? (m[1] ?? null) : null;
    const date = m ? (m[2] ?? "").trim() : null;
    const dateValid = date !== null && HISTORY_DATE_RE.test(date);

    const bullets: string[] = [];
    const strayLines: string[] = [];
    for (let i = start + 1; i < end; i++) {
      const line = (lines[i] ?? "").trim();
      if (line === "") continue;
      const bm = BULLET_RE.exec(line);
      if (bm) {
        bullets.push((bm[1] ?? "").trim());
      } else {
        strayLines.push(line);
      }
    }

    entries.push({ headingRaw, version, date, dateValid, bullets, strayLines });
  }
  return entries;
}

/**
 * Compare two version strings by dot-separated segment: numeric segments
 * compare numerically, non-numeric segments compare lexically. Good enough
 * for the `<major>.<minor>[.<patch>]` versions HISTORY.md and `.kmn` files
 * use; not a full semver implementation.
 */
export function compareVersions(a: string, b: string): number {
  const pa = a.split(".");
  const pb = b.split(".");
  const len = Math.max(pa.length, pb.length);
  for (let i = 0; i < len; i++) {
    const sa = pa[i] ?? "0";
    const sb = pb[i] ?? "0";
    const na = Number(sa);
    const nb = Number(sb);
    if (Number.isNaN(na) || Number.isNaN(nb)) {
      if (sa !== sb) return sa < sb ? -1 : 1;
      continue;
    }
    if (na !== nb) return na - nb;
  }
  return 0;
}

// ---------------------------------------------------------------------------
// README.md "Supported Platforms" parsing (5.7)
// ---------------------------------------------------------------------------

const README_PLATFORMS_HEADING = "## Supported Platforms";

/**
 * Parse the platform list `renderReadmeMd` (engine `helpDocsRender.ts`)
 * writes under "## Supported Platforms" — a run of `- <platform>` bullets
 * ending at the next heading or end of file. `[]` when the section is absent.
 */
export function parseReadmePlatforms(readmeMdText: string): string[] {
  const lines = readmeMdText.split(/\r\n|\r|\n/);
  const headingIdx = lines.findIndex((l) => l.trim() === README_PLATFORMS_HEADING);
  if (headingIdx === -1) return [];

  const platforms: string[] = [];
  for (let i = headingIdx + 1; i < lines.length; i++) {
    const line = lines[i] ?? "";
    if (/^##\s+/.test(line.trim())) break;
    const m = /^-\s+(.*)$/.exec(line.trim());
    if (m) platforms.push((m[1] ?? "").trim());
  }
  return platforms;
}

// ---------------------------------------------------------------------------
// $pagename parsing / formatting (11.7)
// ---------------------------------------------------------------------------

/** Reverse `phpSingleQuoteEscape` (engine `escapeHtml.ts`): `\\` then `\'`. */
function phpSingleQuoteUnescape(s: string): string {
  let out = "";
  for (let i = 0; i < s.length; i++) {
    const ch = s[i]!;
    if (ch === "\\" && i + 1 < s.length) {
      const next = s[i + 1]!;
      if (next === "\\" || next === "'") {
        out += next;
        i++;
        continue;
      }
    }
    out += ch;
  }
  return out;
}

/** Parse the `$pagename = '...'` assignment out of a help.php text, or `null` if absent. */
export function parsePagename(phpText: string): string | null {
  const m = /\$pagename\s*=\s*'((?:\\.|[^'\\])*)'/.exec(phpText);
  if (!m) return null;
  return phpSingleQuoteUnescape(m[1] ?? "");
}

/**
 * The expected `$pagename` value for a display name (contracts/help-header.md,
 * criterion 11.7): "<Display Name> Keyboard Help", or "<Display Name> Help"
 * when the display name already ends with the word "Keyboard". Mirrors
 * `packageDocs.ts`'s `helpSitePageName` in the engine package — duplicated
 * here because keyboard-lint cannot import the engine (`lint-not-to-engine`);
 * the help-header contract is the source of truth both converge on.
 */
export function expectedPagename(displayName: string): string {
  const name = displayName.replace(/\s+/g, " ").trim();
  return /\bkeyboard$/i.test(name) ? `${name} Help` : `${name} Keyboard Help`;
}

// ---------------------------------------------------------------------------
// data-states parsing (11.6)
// ---------------------------------------------------------------------------

const DATA_STATES_RE = /\bdata-states\s*=\s*"([^"]*)"|\bdata-states\s*=\s*'([^']*)'/gi;

/** Every layer id named across all `data-states="..."` attributes, deduped, in document order. */
export function extractDataStatesLayers(html: string): string[] {
  const layers: string[] = [];
  const seen = new Set<string>();
  let m: RegExpExecArray | null;
  DATA_STATES_RE.lastIndex = 0;
  while ((m = DATA_STATES_RE.exec(html)) !== null) {
    const raw = m[1] ?? m[2] ?? "";
    for (const part of raw.split(/[,\s]+/)) {
      const name = part.trim();
      if (name !== "" && !seen.has(name)) {
        seen.add(name);
        layers.push(name);
      }
    }
  }
  return layers;
}

// ---------------------------------------------------------------------------
// Body normalization (11.9) and inline-style extraction (11.10)
// ---------------------------------------------------------------------------

const KEYBOARD_LAYOUT_SECTION_RE = /<h2>Keyboard Layout<\/h2>[\s\S]*?(?=<h2>|<\/body>|$)/i;

/** Strip a leading `<?php ... ?>` header block (the help-site header, spec 076 FR-003). */
export function stripPhpHeader(text: string): string {
  return text.replace(/^\s*<\?php[\s\S]*?\?>\s*/, "");
}

/** Strip the welcome-only "Keyboard Layout" section (spec 076 FR-004) so welcome/help bodies compare fairly. */
export function stripKeyboardLayoutSection(html: string): string {
  return html.replace(KEYBOARD_LAYOUT_SECTION_RE, "");
}

function collapseWhitespace(s: string): string {
  return s.replace(/\s+/g, " ").trim();
}

/**
 * Normalize a welcome/help body for the 11.9 parity comparison: strip the PHP
 * header (help-only) and the "Keyboard Layout" section (welcome-only), then
 * collapse whitespace so formatting differences don't register as content
 * differences (criterion 11.9 wording).
 */
export function normalizeDocBody(html: string): string {
  return collapseWhitespace(stripKeyboardLayoutSection(stripPhpHeader(html)));
}

const STYLE_ATTR_RE = /\bstyle\s*=\s*"([^"]*)"|\bstyle\s*=\s*'([^']*)'/gi;
const STYLE_BLOCK_RE = /<style\b[^>]*>([\s\S]*?)<\/style>/gi;

/**
 * Strip whitespace entirely rather than collapsing it to one space: unlike
 * HTML body text, CSS whitespace never separates otherwise-adjacent tokens
 * (`color:red` and `color: red` render identically), so "modulo non-rendering
 * whitespace" (criterion 11.10) means whitespace-insensitive, not just
 * run-collapsed.
 */
function stripAllWhitespace(s: string): string {
  return s.replace(/\s+/g, "");
}

/**
 * Every inline style declaration in a document, in document order: `style="..."`
 * attribute values followed by `<style>...</style>` block contents, each with
 * whitespace stripped entirely (criterion 11.10: "identical modulo non-rendering
 * whitespace").
 */
export function extractInlineStyles(html: string): string[] {
  const styles: string[] = [];
  let m: RegExpExecArray | null;
  STYLE_ATTR_RE.lastIndex = 0;
  while ((m = STYLE_ATTR_RE.exec(html)) !== null) {
    styles.push(stripAllWhitespace(m[1] ?? m[2] ?? ""));
  }
  STYLE_BLOCK_RE.lastIndex = 0;
  while ((m = STYLE_BLOCK_RE.exec(html)) !== null) {
    styles.push(stripAllWhitespace(m[1] ?? ""));
  }
  return styles;
}

/** Array equality by value (used to compare extracted style lists). */
export function arraysEqual(a: readonly string[], b: readonly string[]): boolean {
  if (a.length !== b.length) return false;
  for (let i = 0; i < a.length; i++) {
    if (a[i] !== b[i]) return false;
  }
  return true;
}

// ---------------------------------------------------------------------------
// Tag-balance scanner (11.5) — the DOMParser deviation, see module header.
// ---------------------------------------------------------------------------

/** HTML void elements: never pushed onto the open-tag stack (no closing tag expected). */
export const VOID_ELEMENTS: ReadonlySet<string> = new Set([
  "area",
  "base",
  "br",
  "col",
  "embed",
  "hr",
  "img",
  "input",
  "link",
  "meta",
  "param",
  "source",
  "track",
  "wbr",
]);

export interface UnbalancedTag {
  tag: string;
  kind: "unclosed" | "mismatched" | "stray-closing";
}

const TAG_RE = /<!--[\s\S]*?-->|<\/([a-zA-Z][a-zA-Z0-9-]*)\s*>|<([a-zA-Z][a-zA-Z0-9-]*)\b([^>]*)>/g;

/**
 * A dependency-free, void-element-aware tag-balance scanner (spec 076
 * research R7 — see module header for why this replaces DOMParser). Finds
 * unclosed elements, elements closed out of nesting order, and stray closing
 * tags with no matching open tag. Comments are skipped; PHP `<?php ... ?>`
 * regions are not special-cased (the header is stripped by callers that need
 * to ignore it).
 */
export function findUnbalancedTags(html: string): UnbalancedTag[] {
  const findings: UnbalancedTag[] = [];
  const stack: string[] = [];
  let m: RegExpExecArray | null;
  TAG_RE.lastIndex = 0;
  while ((m = TAG_RE.exec(html)) !== null) {
    const closingName = m[1];
    const openingName = m[2];
    const attrs = m[3] ?? "";
    if (closingName !== undefined) {
      const name = closingName.toLowerCase();
      const idx = stack.lastIndexOf(name);
      if (idx === -1) {
        findings.push({ tag: name, kind: "stray-closing" });
      } else {
        for (let i = stack.length - 1; i > idx; i--) {
          findings.push({ tag: stack[i]!, kind: "mismatched" });
        }
        stack.length = idx;
      }
    } else if (openingName !== undefined) {
      const name = openingName.toLowerCase();
      const selfClosed = /\/\s*$/.test(attrs);
      if (!VOID_ELEMENTS.has(name) && !selfClosed) {
        stack.push(name);
      }
    }
  }
  for (const tag of stack) {
    findings.push({ tag, kind: "unclosed" });
  }
  return findings;
}
