// Package-descriptor coverage for the OUTPUT path (spec 057 T017/T019/T020/T039).
//
// WHY THIS IS A SEPARATE FILE FROM serializeWorkingCopy.test.ts
//
// That file mocks `projectWorkingCopyVfs` — correctly, because what it tests is the
// arguments serializeWorkingCopy assembles. But the descriptor is written BY the
// projection, so a descriptor assertion there could only pass by having the test
// seed the descriptor itself. That is precisely what FR-017 forbids: "a test
// asserting behaviour of the package descriptor MUST NOT supply the descriptor it
// is proving exists." The pre-057 adapt-path tests passed an explicit `kpsContent`
// into their store seeder, which is how the adapt track shipped no descriptor at
// all with a green suite (E-6/E-7).
//
// So: the REAL projection runs here. `toZip` is the only thing stubbed, and only to
// capture the VirtualFS it is handed — the tree that becomes the archive. Asserting
// on that tree is asserting on the delivered artifact.
//
// Both tracks are covered, which FR-017 also requires.

import { describe, it, expect, vi, beforeEach, afterEach } from "vitest";
import { useWorkingCopyStore } from "../stores/workingCopyStore.ts";
import { createVirtualFS } from "@keyboard-studio/contracts";
import type { Pattern, VirtualFS } from "@keyboard-studio/contracts";
import { makeTestIR, basicKbdus } from "@keyboard-studio/contracts/fixtures";

// ---------------------------------------------------------------------------
// Only the services boundary is stubbed. The projection is REAL.
// ---------------------------------------------------------------------------

/** The VFS handed to toZip — i.e. the tree the archive is built from. */
let deliveredVfs: VirtualFS | null = null;

const mockToZip = vi.fn(async (vfs: VirtualFS) => {
  deliveredVfs = vfs;
  return new Uint8Array([1, 2, 3]);
});
const mockGetById = vi.fn(async (_id: string): Promise<Pattern | undefined> => undefined);

vi.mock("./services.ts", () => ({
  getToZip: vi.fn(async () => mockToZip),
  getPatternLibraryService: vi.fn(() => ({ getById: mockGetById })),
}));

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * The `.kmn` both tracks start from. `&TARGETS 'any'` so the generated `<Files>`
 * list includes the `.js`, which is what makes the "derived from what this build
 * emits" guarantee observable.
 */
const BASE_KMN = "store(&NAME) 'US English (Basic)'\nstore(&TARGETS) 'any'\nc test\n";

/**
 * Seed the ADAPT track with NO descriptor — the state a real import leaves behind,
 * because `fetchKeyboardSourceToVfs` deliberately refuses to fetch the base's raw
 * `.kps` (it references compiled `../build/*.kmx` artifacts).
 *
 * Deliberately takes no `kpsContent` parameter. Supplying one is what let the
 * pre-057 tests "prove" a descriptor that the shipped code never wrote.
 */
function seedAdaptTrackWithoutDescriptor(originalVersion = "1.0") {
  const vfs = createVirtualFS([
    { path: "source/basic_kbdus.kmn", content: BASE_KMN, isBinary: false },
  ]);
  const ir = makeTestIR([]);
  ir.header.version = originalVersion;
  useWorkingCopyStore.getState().instantiateFromExisting(basicKbdus, { vfs, ir });
  return { vfs, ir };
}

/** Seed the COPY track, whose scaffolded descriptor declares the BASE's language. */
function seedCopyTrack(baseKpsLanguageTag = "en") {
  const vfs = createVirtualFS([
    { path: "source/basic_kbdus.kmn", content: BASE_KMN, isBinary: false },
    {
      path: "source/basic_kbdus.kps",
      content:
        '<?xml version="1.0" encoding="utf-8"?>\n' +
        "<Package>\n" +
        '  <Info>\n    <Name URL="">US English (Basic)</Name>\n' +
        '    <Description URL="">US English (Basic) keyboard, generated by Keyboard Studio.</Description>\n  </Info>\n' +
        "  <Keyboards>\n    <Keyboard>\n      <Name>US English (Basic)</Name>\n" +
        "      <ID>basic_kbdus</ID>\n      <Version>1.0</Version>\n      <Languages>\n" +
        `        <Language ID="${baseKpsLanguageTag}">${baseKpsLanguageTag}</Language>\n` +
        "      </Languages>\n    </Keyboard>\n  </Keyboards>\n" +
        "</Package>\n",
      isBinary: false,
    },
  ]);
  const ir = makeTestIR([]);
  ir.header.version = "1.0";
  useWorkingCopyStore.getState().instantiateFromBase(basicKbdus, { vfs, ir });
  return { vfs, ir };
}

/** The author's identity answers, as the identity-lite series composes them. */
const AUTHOR_IDENTITY = {
  displayName: "Bambara",
  bcp47: "bm-Latn",
  languageName: "Bambara",
};

function descriptorText(keyboardId: string): string {
  expect(deliveredVfs, "toZip must have been handed a VFS").not.toBeNull();
  const entry = deliveredVfs!.get(`source/${keyboardId}.kps`);
  expect(entry, `the delivered archive must contain source/${keyboardId}.kps`).toBeDefined();
  expect(typeof entry!.content).toBe("string");
  return entry!.content as string;
}

function languageElements(kps: string): string[] {
  return kps.match(/<Language\b[^>]*>[^<]*<\/Language>/g) ?? [];
}

beforeEach(() => {
  useWorkingCopyStore.getState().reset();
  deliveredVfs = null;
  vi.clearAllMocks();
});

afterEach(() => {
  useWorkingCopyStore.getState().reset();
  deliveredVfs = null;
  vi.clearAllMocks();
});

// ---------------------------------------------------------------------------
// US3 — the adapt track ships a descriptor (T017)
// ---------------------------------------------------------------------------

describe("delivered artifact — adapt track (US3, FR-005, FR-006)", () => {
  it("contains a descriptor declaring the author's language and name, without one being seeded", async () => {
    const { serializeWorkingCopy } = await import("./serializeWorkingCopy.ts");
    seedAdaptTrackWithoutDescriptor("1.0");
    useWorkingCopyStore.getState().setIdentity(AUTHOR_IDENTITY);

    const result = await serializeWorkingCopy();
    expect(result).not.toBeNull();

    const kps = descriptorText("basic_kbdus");
    expect(languageElements(kps)).toEqual(['<Language ID="bm-Latn">Bambara</Language>']);
    expect(kps).toContain('<Name URL="">Bambara</Name>');
    // Not the base's language, even though instantiateFromExisting seeded
    // identity.bcp47 from `basicKbdus.languages[0]` ("en") before the author
    // answered (SC-002).
    expect(kps).not.toContain('<Language ID="en">en</Language>');
  });

  it("derives the Files list from what this build emits, not from the base's repo (D-09)", async () => {
    const { serializeWorkingCopy } = await import("./serializeWorkingCopy.ts");
    seedAdaptTrackWithoutDescriptor("1.0");
    useWorkingCopyStore.getState().setIdentity(AUTHOR_IDENTITY);
    await serializeWorkingCopy();

    const kps = descriptorText("basic_kbdus");
    expect(kps).toContain("<Name>..\\build\\basic_kbdus.kmx</Name>");
    // `&TARGETS 'any'` emits a `.js`; a `<Files>` list that named artifacts this
    // build does not produce is what fails kmc with KM04003.
    expect(kps).toContain("<Name>..\\build\\basic_kbdus.js</Name>");
  });

  // FR-008 / US3-2. The pre-057 `<Version>` regex patch in serializeWorkingCopy
  // silently no-opped on the adapt track because there was no descriptor to patch
  // (E-6). Now there always is one, so the no-op is unreachable and the two
  // versions must agree.
  it("keeps the descriptor's keyboard version in agreement with the bumped source (FR-008)", async () => {
    const { serializeWorkingCopy } = await import("./serializeWorkingCopy.ts");
    seedAdaptTrackWithoutDescriptor("2.0");
    useWorkingCopyStore.getState().setIdentity(AUTHOR_IDENTITY);

    const result = await serializeWorkingCopy();
    expect(result!.version).toBe("2.1");

    const kps = descriptorText("basic_kbdus");
    expect(kps).toContain(`<Version>${result!.version}</Version>`);
    // And the silent-no-op warning must NOT have fired: there was a descriptor.
    expect(result!.warnings).not.toContain(
      "[adapt] could not update .kps <Version> to 2.1; .kps and .kmn versions may differ in the output",
    );
  });

  // FR-006 / US3-3: a failure to write is NAMED. Here the descriptor is generated
  // rather than patched, and the writer says so on the download path.
  it("names the generation on the download path rather than doing it silently (FR-006)", async () => {
    const { serializeWorkingCopy } = await import("./serializeWorkingCopy.ts");
    seedAdaptTrackWithoutDescriptor("1.0");
    useWorkingCopyStore.getState().setIdentity(AUTHOR_IDENTITY);

    const result = await serializeWorkingCopy();
    expect(result!.warnings).toContain(
      "[package-descriptor] generated a package descriptor for basic_kbdus (none was present)",
    );
  });

  it("names an unwritable descriptor on the download path instead of failing silently", async () => {
    const { serializeWorkingCopy } = await import("./serializeWorkingCopy.ts");
    const vfs = createVirtualFS([
      { path: "source/basic_kbdus.kmn", content: BASE_KMN, isBinary: false },
      // A descriptor this module cannot parse: no <Info>, no <Keyboards>.
      { path: "source/basic_kbdus.kps", content: "not a package at all", isBinary: false },
    ]);
    const ir = makeTestIR([]);
    ir.header.version = "1.0";
    useWorkingCopyStore.getState().instantiateFromExisting(basicKbdus, { vfs, ir });
    useWorkingCopyStore.getState().setIdentity(AUTHOR_IDENTITY);

    const result = await serializeWorkingCopy();
    expect(result).not.toBeNull();
    const descriptorWarnings = result!.warnings.filter((w) =>
      w.startsWith("[package-descriptor] could not write identity into"),
    );
    expect(descriptorWarnings).toHaveLength(1);
    expect(descriptorWarnings[0]).toContain("source/basic_kbdus.kps");
    // The archive is still produced — a descriptor that cannot be written is a
    // named warning, not an aborted download.
    expect(result!.bytes.length).toBeGreaterThan(0);
  });
});

// ---------------------------------------------------------------------------
// US1 — the copy track's delivered descriptor (T039)
// ---------------------------------------------------------------------------

describe("delivered artifact — copy track (US1, FR-017)", () => {
  it("replaces the base's declared language with the author's", async () => {
    const { serializeWorkingCopy } = await import("./serializeWorkingCopy.ts");
    seedCopyTrack("en");
    useWorkingCopyStore.getState().setIdentity(AUTHOR_IDENTITY);

    await serializeWorkingCopy();

    const kps = descriptorText("basic_kbdus");
    expect(languageElements(kps)).toEqual(['<Language ID="bm-Latn">Bambara</Language>']);
    expect(kps).not.toContain('<Language ID="en">en</Language>');
    expect(kps).toContain('<Name URL="">Bambara</Name>');
    expect(kps).toContain(
      '<Description URL="">Bambara keyboard, generated by Keyboard Studio.</Description>',
    );
  });

  it("carries the identity through the id rename onto the renamed descriptor", async () => {
    const { serializeWorkingCopy } = await import("./serializeWorkingCopy.ts");
    seedCopyTrack("en");
    useWorkingCopyStore.getState().setIdentity({ ...AUTHOR_IDENTITY, keyboardId: "bm_sil" });

    const result = await serializeWorkingCopy();
    expect(result!.keyboardId).toBe("bm_sil");

    expect(deliveredVfs!.get("source/basic_kbdus.kps")).toBeUndefined();
    const kps = descriptorText("bm_sil");
    expect(languageElements(kps)).toEqual(['<Language ID="bm-Latn">Bambara</Language>']);
    expect(kps).toContain('<Name URL="">Bambara</Name>');
    expect(kps).toContain("<ID>bm_sil</ID>");
  });

  // US1-3 / FR-007: an optional answer left blank leaves the descriptor
  // well-formed and buildable — and still not declaring the base's language.
  it("declares the und placeholder, never the base's language, on a blank code", async () => {
    const { serializeWorkingCopy } = await import("./serializeWorkingCopy.ts");
    seedCopyTrack("en");
    useWorkingCopyStore.getState().setIdentity({ displayName: "Bambara" });

    await serializeWorkingCopy();

    const kps = descriptorText("basic_kbdus");
    expect(languageElements(kps)).toEqual(['<Language ID="und">und</Language>']);
    expect(kps).not.toContain('<Language ID="en">en</Language>');
    // Still buildable: kmc needs a non-blank Description and a package version.
    expect(kps).toContain('<Description URL="">Bambara keyboard, generated by Keyboard Studio.</Description>');
  });
});

// ---------------------------------------------------------------------------
// FR-004 / FR-005 — one writer, one descriptor
// ---------------------------------------------------------------------------

describe("delivered artifact — a single descriptor writer (FR-004, FR-005)", () => {
  it("gives the pull-request tree and the zip tree the identical descriptor", async () => {
    const { serializeWorkingCopy, projectWorkingCopyForOutput } = await import(
      "./serializeWorkingCopy.ts"
    );
    seedCopyTrack("en");
    useWorkingCopyStore.getState().setIdentity(AUTHOR_IDENTITY);

    // The PR path consumes projectWorkingCopyForOutput's VFS directly; the zip
    // path feeds the same projection to toZip. FR-004/SC-005 require them equal.
    const projected = await projectWorkingCopyForOutput();
    await serializeWorkingCopy();

    const prDescriptor = projected!.vfs.get("source/basic_kbdus.kps")!.content;
    expect(prDescriptor).toBe(descriptorText("basic_kbdus"));
  });
});
