// Tests for the package-descriptor builder (spec 059 T009).
//
// What these assert is the identity contract, not the whole file shape: the four
// elements the writer owns (contracts/package-descriptor.md §2), and the two
// fallbacks that must NOT reach for the base keyboard's values (FR-007, SC-002).

import { describe, it, expect } from "vitest";
import { buildKpsContent, buildLanguageElement } from "./build.js";

/** A `.kmn` with web targets and a visual keyboard, so `<Files>` is fully populated. */
const KMN = [
  "store(&NAME) 'Bambara'",
  "store(&VERSION) '14.0'",
  "store(&TARGETS) 'any'",
  "store(&VISUALKEYBOARD) 'bm_sil.kvk'",
  "begin Unicode > use(main)",
  "group(main) using keys",
  "",
].join("\n");

/** The single `<Language …>` line, whitespace-normalized. */
function languageLine(kps: string): string | undefined {
  return /<Language\b[^>]*>[^<]*<\/Language>/.exec(kps)?.[0];
}

function allLanguageLines(kps: string): string[] {
  return kps.match(/<Language\b[^>]*>[^<]*<\/Language>/g) ?? [];
}

describe("buildKpsContent — the language block (FR-001, FR-002)", () => {
  it("declares the author's tag with the language name as element text", () => {
    const kps = buildKpsContent(
      "bm_sil",
      { displayName: "Bambara", languageTag: "bm-Latn", languageName: "Bambara" },
      KMN,
    );
    expect(languageLine(kps)).toBe('<Language ID="bm-Latn">Bambara</Language>');
  });

  it("declares exactly ONE language, never a list", () => {
    const kps = buildKpsContent(
      "bm_sil",
      { displayName: "Bambara", languageTag: "bm-Latn", languageName: "Bambara" },
      KMN,
    );
    expect(allLanguageLines(kps)).toHaveLength(1);
  });

  it("falls back to the tag as display text when the name is blank (FR-002)", () => {
    const kps = buildKpsContent(
      "bm_sil",
      { displayName: "Bambara", languageTag: "bm-Latn", languageName: "   " },
      KMN,
    );
    expect(languageLine(kps)).toBe('<Language ID="bm-Latn">bm-Latn</Language>');
  });

  it("falls back to the tag as display text when the name is absent", () => {
    const kps = buildKpsContent("bm_sil", { displayName: "Bambara", languageTag: "bm" }, KMN);
    expect(languageLine(kps)).toBe('<Language ID="bm">bm</Language>');
  });

  // US1-3 / FR-007: the blank-code edge case. The placeholder is the writer's own
  // pre-existing `und`, so no new convention is introduced — and critically it is
  // NOT the base keyboard's tag, which the writer is no longer even told.
  it("uses the well-formed und placeholder when the tag is absent (US1-3, FR-007)", () => {
    const kps = buildKpsContent("bm_sil", { displayName: "Bambara" }, KMN);
    expect(languageLine(kps)).toBe('<Language ID="und">und</Language>');
  });

  it("uses the und placeholder when the tag is blank, not the name", () => {
    const kps = buildKpsContent(
      "bm_sil",
      { displayName: "Bambara", languageTag: "  ", languageName: "Bambara" },
      KMN,
    );
    // The NAME still shows through as display text — it is the ID that has no
    // author value to declare. What must never appear is a base tag.
    expect(languageLine(kps)).toBe('<Language ID="und">Bambara</Language>');
  });

  it("never declares a base keyboard's tag, because it is never given one (SC-002)", () => {
    // The signature itself is the guarantee: there is no parameter through which
    // `fr` could arrive. This pins that the pre-057 `languages: string[]` shape is
    // gone rather than merely unused.
    const kps = buildKpsContent("bm_sil", { displayName: "Bambara" }, KMN);
    expect(kps).not.toContain('ID="fr"');
  });
});

describe("buildKpsContent — the display-name elements (FR-003)", () => {
  it("tracks displayName in Info/Name, Info/Description, and Keyboard/Name", () => {
    const kps = buildKpsContent(
      "bm_sil",
      { displayName: "Bambara (SIL)", languageTag: "bm-Latn" },
      KMN,
    );
    expect(kps).toContain('<Name URL="">Bambara (SIL)</Name>');
    expect(kps).toContain(
      '<Description URL="">Bambara (SIL) keyboard, generated by Keyboard Studio.</Description>',
    );
    // The keyboard's own <Name>, inside <Keyboards><Keyboard>.
    const keyboardBlock = /<Keyboards>[\s\S]*?<\/Keyboards>/.exec(kps)?.[0] ?? "";
    expect(keyboardBlock).toContain("<Name>Bambara (SIL)</Name>");
  });

  it("falls back to the keyboard id rather than emitting a blank Name (kmc KM09010)", () => {
    const kps = buildKpsContent("bm_sil", { displayName: "   ", languageTag: "bm" }, KMN);
    expect(kps).toContain('<Name URL="">bm_sil</Name>');
    expect(kps).not.toContain('<Name URL=""></Name>');
  });
});

describe("buildKpsContent — escaping (contract §3)", () => {
  it("produces well-formed XML for a display name containing & and <", () => {
    const kps = buildKpsContent(
      "kb",
      { displayName: "A & B <sil>", languageTag: "bm", languageName: "Bam & Ba" },
      KMN,
    );
    expect(kps).toContain("<Name URL=\"\">A &amp; B &lt;sil&gt;</Name>");
    expect(kps).toContain("<Language ID=\"bm\">Bam &amp; Ba</Language>");
    // No raw `&` survives anywhere: every one is the head of an entity.
    expect(kps.match(/&(?!amp;|lt;|gt;|quot;|#39;)/g)).toBeNull();
  });

  it("escapes a tag containing a quote so the attribute stays closed", () => {
    const element = buildLanguageElement({ displayName: "x", languageTag: 'bm"evil' });
    expect(element).toBe('<Language ID="bm&quot;evil">bm&quot;evil</Language>');
  });
});

describe("buildKpsContent — <WebSite> (spec 061 FR-012, research D-06)", () => {
  it("emits <WebSite> from websiteUrl, URL duplicated as attribute and text", () => {
    const kps = buildKpsContent(
      "bm_sil",
      { displayName: "Bambara", websiteUrl: "https://example.com" },
      KMN,
    );
    expect(kps).toContain(
      '<WebSite URL="https://example.com">https://example.com</WebSite>',
    );
  });

  it("omits <WebSite> entirely when websiteUrl is absent or blank", () => {
    expect(buildKpsContent("bm_sil", { displayName: "Bambara" }, KMN)).not.toContain("WebSite");
    expect(
      buildKpsContent("bm_sil", { displayName: "Bambara", websiteUrl: "   " }, KMN),
    ).not.toContain("WebSite");
  });

  it("escapes the URL", () => {
    const kps = buildKpsContent(
      "bm_sil",
      { displayName: "Bambara", websiteUrl: "https://example.com/?a=1&b=2" },
      KMN,
    );
    expect(kps).toContain("https://example.com/?a=1&amp;b=2");
    expect(kps).not.toMatch(/&(?!amp;|lt;|gt;|quot;|#39;)/);
  });
});

describe("buildKpsContent — the parts this feature does NOT own (contract §2)", () => {
  it("keeps the Files list derived from the emitted .kmn's targets", () => {
    const kps = buildKpsContent("bm_sil", { displayName: "Bambara" }, KMN);
    expect(kps).toContain("<Name>..\\build\\bm_sil.kmx</Name>");
    expect(kps).toContain("<Name>..\\build\\bm_sil.js</Name>"); // &TARGETS 'any'
    expect(kps).toContain("<Name>..\\build\\bm_sil.kvk</Name>"); // &VISUALKEYBOARD present
  });

  it("omits the .js entry for a desktop-only target", () => {
    const desktopOnly = KMN.replace("store(&TARGETS) 'any'", "store(&TARGETS) 'windows'");
    const kps = buildKpsContent("bm_sil", { displayName: "Bambara" }, desktopOnly);
    expect(kps).not.toContain("<Name>..\\build\\bm_sil.js</Name>");
  });

  it("propagates the version argument into Keyboard/Version (FR-008)", () => {
    const kps = buildKpsContent("bm_sil", { displayName: "Bambara" }, KMN, "2.3");
    expect(kps).toContain("<Version>2.3</Version>");
  });

  it("defaults the version to 1.0", () => {
    const kps = buildKpsContent("bm_sil", { displayName: "Bambara" }, KMN);
    expect(kps).toContain("<Version>1.0</Version>");
  });

  it("still emits the buildable shape kmc requires", () => {
    const kps = buildKpsContent("bm_sil", { displayName: "Bambara" }, KMN);
    expect(kps).toContain("<FollowKeyboardVersion/>");
    expect(kps).toContain("<ReadMeFile>readme.htm</ReadMeFile>");
    expect(kps).toContain("<WelcomeFile>welcome.htm</WelcomeFile>");
    expect(kps.startsWith('<?xml version="1.0" encoding="utf-8"?>')).toBe(true);
  });
});
