// Tests for applyIdentityToKps (spec 059 T010).
//
// The two paths that matter are the two authoring tracks: PATCH (the copy track,
// whose scaffolded descriptor declares the base's language) and GENERATE (the
// adapt track, which has no descriptor at all). Plus the failure modes, which must
// warn rather than throw — a silent no-op is the defect this feature removes.

import { describe, it, expect } from "vitest";
import { createVirtualFS } from "@keyboard-studio/contracts";
import { applyIdentityToKps } from "./patch.js";
import { buildKpsContent } from "./build.js";

const KMN = [
  "store(&NAME) 'Bambara'",
  "store(&VERSION) '14.0'",
  "store(&TARGETS) 'any'",
  "begin Unicode > use(main)",
  "group(main) using keys",
  "",
].join("\n");

/** The scaffolder's output for a French base — what the copy track actually holds. */
function frenchBaseDescriptor(id = "bm_sil"): string {
  return buildKpsContent(id, { displayName: "French AZERTY", languageTag: "fr" }, KMN, "1.0");
}

function vfsWith(path: string, content: string) {
  const vfs = createVirtualFS();
  vfs.set(path, content, false);
  return vfs;
}

function textAt(vfs: ReturnType<typeof createVirtualFS>, path: string): string {
  const entry = vfs.get(path);
  if (entry === undefined || typeof entry.content !== "string") {
    throw new Error(`no text entry at ${path}`);
  }
  return entry.content;
}

function allLanguageLines(kps: string): string[] {
  return kps.match(/<Language\b[^>]*>[^<]*<\/Language>/g) ?? [];
}

describe("applyIdentityToKps — patching an existing descriptor (US1, SC-002)", () => {
  it("replaces the base's language TOTALLY, leaving only the author's", () => {
    const vfs = vfsWith("source/bm_sil.kps", frenchBaseDescriptor());
    const result = applyIdentityToKps(
      vfs,
      "bm_sil",
      { displayName: "Bambara", languageTag: "bm-Latn", languageName: "Bambara" },
      KMN,
    );

    const kps = textAt(vfs, "source/bm_sil.kps");
    expect(allLanguageLines(kps)).toEqual(['<Language ID="bm-Latn">Bambara</Language>']);
    expect(kps).not.toContain('ID="fr"');
    expect(result.generated).toBe(false);
    expect(result.warnings).toEqual([]);
  });

  it("rewrites Info/Name, Info/Description and Keyboard/Name (FR-003)", () => {
    const vfs = vfsWith("source/bm_sil.kps", frenchBaseDescriptor());
    applyIdentityToKps(vfs, "bm_sil", { displayName: "Bambara", languageTag: "bm" }, KMN);

    const kps = textAt(vfs, "source/bm_sil.kps");
    expect(kps).toContain('<Name URL="">Bambara</Name>');
    expect(kps).toContain(
      '<Description URL="">Bambara keyboard, generated by Keyboard Studio.</Description>',
    );
    expect(kps).not.toContain("French AZERTY");
  });

  it("leaves Files, System, Options and Version untouched (contract §2)", () => {
    const before = frenchBaseDescriptor();
    const vfs = vfsWith("source/bm_sil.kps", before);
    applyIdentityToKps(
      vfs,
      "bm_sil",
      { displayName: "Bambara", languageTag: "bm" },
      KMN,
      // A version argument is accepted but must NOT rewrite an existing <Version>:
      // the adapt path's bump patch owns that element.
      "9.9",
    );
    const after = textAt(vfs, "source/bm_sil.kps");

    for (const re of [
      /<Files>[\s\S]*?<\/Files>/,
      /<System>[\s\S]*?<\/System>/,
      /<Options>[\s\S]*?<\/Options>/,
      /<Version>[^<]*<\/Version>/,
    ]) {
      expect(re.exec(after)?.[0]).toBe(re.exec(before)?.[0]);
    }
    expect(after).toContain("<Version>1.0</Version>");
  });

  it("preserves a URL attribute on Info/Name rather than dropping it", () => {
    const withUrl = frenchBaseDescriptor().replace(
      '<Name URL="">French AZERTY</Name>',
      '<Name URL="https://example.org/">French AZERTY</Name>',
    );
    const vfs = vfsWith("source/bm_sil.kps", withUrl);
    applyIdentityToKps(vfs, "bm_sil", { displayName: "Bambara", languageTag: "bm" }, KMN);
    expect(textAt(vfs, "source/bm_sil.kps")).toContain(
      '<Name URL="https://example.org/">Bambara</Name>',
    );
  });

  it("declares the author's tag even when the descriptor had no Languages block", () => {
    const noLanguages = frenchBaseDescriptor().replace(
      /\s*<Languages>[\s\S]*?<\/Languages>/,
      "",
    );
    expect(noLanguages).not.toContain("<Languages>");
    const vfs = vfsWith("source/bm_sil.kps", noLanguages);
    const result = applyIdentityToKps(
      vfs,
      "bm_sil",
      { displayName: "Bambara", languageTag: "bm-Latn", languageName: "Bambara" },
      KMN,
    );
    expect(allLanguageLines(textAt(vfs, "source/bm_sil.kps"))).toEqual([
      '<Language ID="bm-Latn">Bambara</Language>',
    ]);
    expect(result.warnings).toEqual([]);
  });

  it("expands a self-closing empty Languages element", () => {
    const selfClosing = frenchBaseDescriptor().replace(
      /<Languages>[\s\S]*?<\/Languages>/,
      "<Languages/>",
    );
    const vfs = vfsWith("source/bm_sil.kps", selfClosing);
    applyIdentityToKps(vfs, "bm_sil", { displayName: "Bambara", languageTag: "bm" }, KMN);
    expect(allLanguageLines(textAt(vfs, "source/bm_sil.kps"))).toEqual([
      '<Language ID="bm">bm</Language>',
    ]);
  });

  it("is idempotent — a second application changes nothing", () => {
    const vfs = vfsWith("source/bm_sil.kps", frenchBaseDescriptor());
    const identity = { displayName: "Bambara", languageTag: "bm-Latn", languageName: "Bambara" };
    applyIdentityToKps(vfs, "bm_sil", identity, KMN);
    const once = textAt(vfs, "source/bm_sil.kps");
    applyIdentityToKps(vfs, "bm_sil", identity, KMN);
    expect(textAt(vfs, "source/bm_sil.kps")).toBe(once);
  });
});

// A blank display name is the SAME defect class as a blank language code, and the
// patch path is where it hides: skipping the write leaves the scaffolded stub's name
// in place, which on the copy track is the base keyboard's (QC P1, FR-003).
describe("applyIdentityToKps — a blank display name never leaves the base's standing", () => {
  it("falls back to the keyboard id rather than keeping the base's name", () => {
    const vfs = vfsWith("source/bm_sil.kps", frenchBaseDescriptor());
    applyIdentityToKps(vfs, "bm_sil", { displayName: "", languageTag: "bm-Latn" }, KMN);

    const kps = textAt(vfs, "source/bm_sil.kps");
    expect(kps).not.toContain("French AZERTY");
    expect(kps).toContain('<Name URL="">bm_sil</Name>');
    expect(kps).toContain(
      '<Description URL="">bm_sil keyboard, generated by Keyboard Studio.</Description>',
    );
    // The keyboard's own <Name> too, not just <Info>'s.
    const keyboardBlock = /<Keyboards>[\s\S]*?<\/Keyboards>/.exec(kps)?.[0] ?? "";
    expect(keyboardBlock).toContain("<Name>bm_sil</Name>");
  });

  it("treats a whitespace-only display name as blank", () => {
    const vfs = vfsWith("source/bm_sil.kps", frenchBaseDescriptor());
    applyIdentityToKps(vfs, "bm_sil", { displayName: "   ", languageTag: "bm" }, KMN);
    expect(textAt(vfs, "source/bm_sil.kps")).not.toContain("French AZERTY");
  });

  it("applies the SAME fallback on the patch and the generate path", () => {
    const identity = { displayName: "", languageTag: "bm-Latn", languageName: "Bambara" };
    // Patch path: an existing descriptor.
    const patched = vfsWith("source/bm_sil.kps", frenchBaseDescriptor());
    applyIdentityToKps(patched, "bm_sil", identity, KMN);
    // Generate path: none present.
    const generated = createVirtualFS();
    applyIdentityToKps(generated, "bm_sil", identity, KMN);

    for (const vfs of [patched, generated]) {
      const kps = textAt(vfs, "source/bm_sil.kps");
      expect(kps).toContain('<Name URL="">bm_sil</Name>');
      expect(allLanguageLines(kps)).toEqual(['<Language ID="bm-Latn">Bambara</Language>']);
    }
  });
});

describe("applyIdentityToKps — <WebSite> on the patch path (spec 061 FR-012)", () => {
  it("inserts <WebSite> right after <Description> when none exists yet", () => {
    const vfs = vfsWith("source/bm_sil.kps", frenchBaseDescriptor());
    applyIdentityToKps(
      vfs,
      "bm_sil",
      { displayName: "Bambara", languageTag: "bm", websiteUrl: "https://example.com" },
      KMN,
    );
    const kps = textAt(vfs, "source/bm_sil.kps");
    expect(kps).toContain(
      '<WebSite URL="https://example.com">https://example.com</WebSite>',
    );
    expect(kps.indexOf("</Description>")).toBeLessThan(kps.indexOf("<WebSite"));
  });

  it("replaces an existing <WebSite> rather than duplicating it", () => {
    const vfs = vfsWith(
      "source/bm_sil.kps",
      buildKpsContent(
        "bm_sil",
        { displayName: "French AZERTY", languageTag: "fr", websiteUrl: "https://old.example.com" },
        KMN,
        "1.0",
      ),
    );
    applyIdentityToKps(
      vfs,
      "bm_sil",
      { displayName: "Bambara", languageTag: "bm", websiteUrl: "https://new.example.com" },
      KMN,
    );
    const kps = textAt(vfs, "source/bm_sil.kps");
    expect(kps).toContain("https://new.example.com");
    expect(kps).not.toContain("old.example.com");
    expect(kps.match(/<WebSite\b/g)).toHaveLength(1);
  });

  it("removes an existing <WebSite> when websiteUrl is now blank (cleared answer)", () => {
    const vfs = vfsWith(
      "source/bm_sil.kps",
      buildKpsContent(
        "bm_sil",
        { displayName: "French AZERTY", languageTag: "fr", websiteUrl: "https://old.example.com" },
        KMN,
        "1.0",
      ),
    );
    applyIdentityToKps(vfs, "bm_sil", { displayName: "Bambara", languageTag: "bm" }, KMN);
    expect(textAt(vfs, "source/bm_sil.kps")).not.toContain("WebSite");
  });

  it("leaves the descriptor unchanged when there was never a <WebSite> and none is given", () => {
    const vfs = vfsWith("source/bm_sil.kps", frenchBaseDescriptor());
    applyIdentityToKps(vfs, "bm_sil", { displayName: "Bambara", languageTag: "bm" }, KMN);
    expect(textAt(vfs, "source/bm_sil.kps")).not.toContain("WebSite");
  });
});

describe("applyIdentityToKps — generating an absent descriptor (US3, FR-006, D-09)", () => {
  it("generates the descriptor and reports that it did", () => {
    const vfs = createVirtualFS();
    const result = applyIdentityToKps(
      vfs,
      "bm_sil",
      { displayName: "Bambara", languageTag: "bm-Latn", languageName: "Bambara" },
      KMN,
      "2.0",
    );

    expect(result.generated).toBe(true);
    expect(result.warnings).toEqual([
      "[package-descriptor] generated a package descriptor for bm_sil (none was present)",
    ]);

    const kps = textAt(vfs, "source/bm_sil.kps");
    expect(allLanguageLines(kps)).toEqual(['<Language ID="bm-Latn">Bambara</Language>']);
    expect(kps).toContain('<Name URL="">Bambara</Name>');
    // FR-008: the version the caller supplied, not a silent 1.0 downgrade.
    expect(kps).toContain("<Version>2.0</Version>");
    // The <Files> list derives from what THIS build emits (D-09) — the reason the
    // descriptor is generated rather than fetched from the base's repo.
    expect(kps).toContain("<Name>..\\build\\bm_sil.kmx</Name>");
  });

  it("produces byte-identical output to a direct build (one writer, FR-005)", () => {
    const identity = { displayName: "Bambara", languageTag: "bm-Latn", languageName: "Bambara" };
    const vfs = createVirtualFS();
    applyIdentityToKps(vfs, "bm_sil", identity, KMN, "2.0");
    expect(textAt(vfs, "source/bm_sil.kps")).toBe(
      buildKpsContent("bm_sil", identity, KMN, "2.0"),
    );
  });
});

describe("applyIdentityToKps — failure names itself rather than throwing (FR-006)", () => {
  it("warns on a descriptor with no recognizable structure", () => {
    const vfs = vfsWith("source/bm_sil.kps", "this is not xml at all");
    let result!: ReturnType<typeof applyIdentityToKps>;
    expect(() => {
      result = applyIdentityToKps(vfs, "bm_sil", { displayName: "Bambara" }, KMN);
    }).not.toThrow();

    expect(result.generated).toBe(false);
    expect(result.warnings).toHaveLength(1);
    expect(result.warnings[0]).toContain("[package-descriptor] could not write identity into");
    expect(result.warnings[0]).toContain("source/bm_sil.kps");
    expect(result.warnings[0]).toContain("no <Info> block");
    expect(result.warnings[0]).toContain("no <Keyboards><Keyboard> block");
    // Not clobbered: the module reports what it could not do, it does not overwrite
    // content it failed to understand.
    expect(textAt(vfs, "source/bm_sil.kps")).toBe("this is not xml at all");
  });

  it("warns when the descriptor entry is binary rather than text", () => {
    const vfs = createVirtualFS();
    vfs.set("source/bm_sil.kps", new Uint8Array([0, 1, 2]), true);
    const result = applyIdentityToKps(vfs, "bm_sil", { displayName: "Bambara" }, KMN);
    expect(result.warnings).toEqual([
      "[package-descriptor] could not write identity into source/bm_sil.kps: descriptor is not text",
    ]);
    expect(result.generated).toBe(false);
  });

  it("emits no emoji in any warning (house convention)", () => {
    const vfs = vfsWith("source/bm_sil.kps", "nope");
    const result = applyIdentityToKps(vfs, "bm_sil", { displayName: "Bambara" }, KMN);
    for (const warning of result.warnings) {
      expect(warning).toMatch(/^\[[a-z-]+\] /);
      // eslint-disable-next-line no-control-regex
      expect(warning).toMatch(/^[\x00-\x7F—‘’]*$/);
    }
  });
});

// ---------------------------------------------------------------------------
// spec 076 FR-002 (T012): the welcome-path migration — the one sanctioned
// <Options>/<Files> write. A pre-076 descriptor (flat `welcome.htm`) is moved to
// the folder form; the files the projection ships beside the page are listed;
// every rewrite is NAMED.
// ---------------------------------------------------------------------------

/** The pre-076 scaffolder stub: today's generate output with the flat name in both places. */
function flatWelcomeDescriptor(id = "bm_sil"): string {
  return frenchBaseDescriptor(id).replace(/welcome\\welcome\.htm/g, "welcome.htm");
}

function fileNames(kps: string): string[] {
  return [...kps.matchAll(/<Name>([^<]*)<\/Name>\s*<FileType>/g)].map((m) => m[1] ?? "");
}

describe("applyIdentityToKps — welcome-path migration (spec 076 FR-002)", () => {
  it("rewrites a flat <WelcomeFile> and <File> to welcome\\welcome.htm and reports both", () => {
    const vfs = vfsWith("source/bm_sil.kps", flatWelcomeDescriptor());
    const result = applyIdentityToKps(vfs, "bm_sil", { displayName: "Bambara", languageTag: "bm" }, KMN);

    const kps = textAt(vfs, "source/bm_sil.kps");
    expect(kps).toContain("<WelcomeFile>welcome\\welcome.htm</WelcomeFile>");
    expect(fileNames(kps)).toContain("welcome\\welcome.htm");
    expect(fileNames(kps)).not.toContain("welcome.htm");
    expect(kps).not.toContain(">welcome.htm<");
    expect(result.warnings).toEqual([
      "[package-descriptor] migrated welcome path in source/bm_sil.kps: <WelcomeFile> welcome.htm -> welcome\\welcome.htm",
      "[package-descriptor] migrated welcome path in source/bm_sil.kps: <File> welcome.htm -> welcome\\welcome.htm",
    ]);
  });

  it("rewrites a BLANK <WelcomeFile></WelcomeFile> too, so the shipped page is never orphaned", () => {
    const blank = frenchBaseDescriptor().replace(
      /<WelcomeFile>[^<]*<\/WelcomeFile>/,
      "<WelcomeFile></WelcomeFile>",
    );
    const vfs = vfsWith("source/bm_sil.kps", blank);
    const result = applyIdentityToKps(vfs, "bm_sil", { displayName: "Bambara" }, KMN);
    expect(textAt(vfs, "source/bm_sil.kps")).toContain("<WelcomeFile>welcome\\welcome.htm</WelcomeFile>");
    expect(result.warnings).toEqual([
      "[package-descriptor] migrated welcome path in source/bm_sil.kps: <WelcomeFile> (blank) -> welcome\\welcome.htm",
    ]);
  });

  it("appends the welcome-folder files the projection ships, once each, and reports them", () => {
    const vfs = vfsWith("source/bm_sil.kps", frenchBaseDescriptor());
    const result = applyIdentityToKps(
      vfs,
      "bm_sil",
      { displayName: "Bambara", languageTag: "bm" },
      KMN,
      undefined,
      ["desktop_default.png", "welcome/desktop_default.png", "ks-layout-phone-default.svg"],
    );

    const names = fileNames(textAt(vfs, "source/bm_sil.kps"));
    expect(names.filter((n) => n === "welcome\\desktop_default.png")).toHaveLength(1);
    expect(names).toContain("welcome\\ks-layout-phone-default.svg");
    // Appended AFTER the existing entries, so nothing the base listed moves.
    expect(names.indexOf("welcome\\ks-layout-phone-default.svg")).toBeGreaterThan(names.indexOf("..\\LICENSE.md"));
    expect(textAt(vfs, "source/bm_sil.kps")).toMatch(
      /<Name>welcome\\desktop_default\.png<\/Name>\s*<FileType>\.png<\/FileType>/,
    );
    expect(result.warnings).toEqual([
      "[package-descriptor] migrated welcome path in source/bm_sil.kps: appended <File> welcome\\desktop_default.png",
      "[package-descriptor] migrated welcome path in source/bm_sil.kps: appended <File> welcome\\ks-layout-phone-default.svg",
    ]);
  });

  it("does not re-append a folder file the descriptor already lists (case-insensitive)", () => {
    const listed = frenchBaseDescriptor().replace(
      "  </Files>",
      "    <File>\n      <Name>welcome\\Chart.PNG</Name>\n      <FileType>.png</FileType>\n    </File>\n  </Files>",
    );
    const vfs = vfsWith("source/bm_sil.kps", listed);
    const result = applyIdentityToKps(vfs, "bm_sil", { displayName: "Bambara" }, KMN, undefined, ["chart.png"]);
    expect(fileNames(textAt(vfs, "source/bm_sil.kps")).filter((n) => n.toLowerCase() === "welcome\\chart.png")).toHaveLength(1);
    expect(result.warnings).toEqual([]);
  });

  it("is a byte-for-byte no-op with no warnings on an already-migrated descriptor (contract §2 still holds)", () => {
    const before = frenchBaseDescriptor();
    const vfs = vfsWith("source/bm_sil.kps", before);
    const result = applyIdentityToKps(vfs, "bm_sil", { displayName: "French AZERTY", languageTag: "fr" }, KMN);
    const after = textAt(vfs, "source/bm_sil.kps");
    expect(after.match(/<Files>[\s\S]*?<\/Files>/)?.[0]).toBe(before.match(/<Files>[\s\S]*?<\/Files>/)?.[0]);
    expect(after.match(/<Options>[\s\S]*?<\/Options>/)?.[0]).toBe(before.match(/<Options>[\s\S]*?<\/Options>/)?.[0]);
    expect(result.warnings).toEqual([]);
  });

  it("leaves a descriptor that lists no welcome page at all alone (no invented entry)", () => {
    const noWelcome = frenchBaseDescriptor()
      .replace(/    <File>\n      <Name>welcome\\welcome\.htm<\/Name>\n      <FileType>\.htm<\/FileType>\n    <\/File>\n/, "")
      .replace(/    <WelcomeFile>[^<]*<\/WelcomeFile>\n/, "");
    const vfs = vfsWith("source/bm_sil.kps", noWelcome);
    const result = applyIdentityToKps(vfs, "bm_sil", { displayName: "Bambara" }, KMN);
    expect(fileNames(textAt(vfs, "source/bm_sil.kps"))).not.toContain("welcome\\welcome.htm");
    expect(result.warnings).toEqual([]);
  });

  it("names the files it could not list when the descriptor has no <Files> block", () => {
    const vfs = vfsWith(
      "source/bm_sil.kps",
      "<Package>\n  <Info>\n    <Name URL=\"\">X</Name>\n  </Info>\n  <Keyboards>\n    <Keyboard>\n      <Name>X</Name>\n      <ID>bm_sil</ID>\n    </Keyboard>\n  </Keyboards>\n</Package>\n",
    );
    const result = applyIdentityToKps(vfs, "bm_sil", { displayName: "Bambara" }, KMN, undefined, ["a.png"]);
    expect(result.warnings).toContain(
      "[package-descriptor] could not list welcome-folder files in source/bm_sil.kps (no <Files> block): a.png",
    );
  });

  it("GENERATES a descriptor that lists the welcome-folder files (adapt track)", () => {
    const vfs = createVirtualFS();
    applyIdentityToKps(vfs, "bm_sil", { displayName: "Bambara" }, KMN, "1.1", ["a.png"]);
    const names = fileNames(textAt(vfs, "source/bm_sil.kps"));
    expect(names).toContain("welcome\\welcome.htm");
    expect(names).toContain("welcome\\a.png");
  });
});
